description: Rumble node

compatible: "zmk,rumble"

properties:
  pwms:
    type: phandle-array
    required: true

  label:
    required: false
    type: string
    description: Human readable string describing the device (used as device_get_binding() argument)
